# Disable MSBuild, Use script.
build: off
version: "{build}"

init:
  - SET PATH=%GOPATH%\bin;c:\go\bin;%PATH%

install:
  - echo %PATH%
  - go env
  - go version

test_script:
  - go test -v -coverprofile=coverage.out -covermode=count ./...

on_success:
  - go get -v -u github.com/mattn/goveralls
  - goveralls -coverprofile=coverage.out -service=appveyor -repotoken %COVERALLS_TOKEN%
